server:
  port: 9999
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/blog?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 584520
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    user:
      name: root
      password: 123



  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDeletestr #全局逻辑删除实体类字段
#      logic-delete-value: 1  #逻辑删除（默认为1）
#      logic-not-delete-value: 0 # 逻辑未删除（默认为0）
